language: node_js # don't install any environment

node_js:
- stable

install: true # skip standard npm installation

before_script:
- npm install --ignore-scripts

script:
- npm run deploy

deploy:
  provider: pages
  local_dir: deploy
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
